"""Physics-informed feature engineering.

The line drawn here is deliberate and is the single most important honesty
decision in the project.

AI4I's labels were generated by deterministic threshold rules over these
sensors (for example: a heat-dissipation failure is recorded when the
process/air temperature differential is below 8.6 K while rotational speed is
below 1380 rpm). It is therefore trivially possible to hand the model those
thresholds as engineered flags and report near-perfect scores -- and equally
trivial for a reviewer to notice that the model was simply told the answer key.

So this module computes **physical quantities only**:

* mechanical power, from torque and angular velocity
* the temperature differential across the process
* the accumulated wear-torque strain product
* a specific-loading ratio and a cooling-adequacy index

These are the quantities any plant engineer derives from this instrumentation.
What is deliberately *not* computed: no threshold comparisons, no
type-specific limits, no binary "at risk" flags, no margin-to-threshold
distances. The model has to discover the operating limits from data, which is
what makes the reported metrics a real result.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from . import config as cfg

RPM_TO_RAD_S = 2.0 * np.pi / 60.0


def add_physics_features(df: pd.DataFrame) -> pd.DataFrame:
    """Derive the physical quantities the models will see.

    Parameters
    ----------
    df
        Frame containing the five raw sensor columns.

    Returns
    -------
    A copy of ``df`` with the engineered columns appended.
    """
    out = df.copy()

    torque = out[cfg.COL_TORQUE].astype(float)
    speed = out[cfg.COL_SPEED].astype(float)
    air = out[cfg.COL_AIR_TEMP].astype(float)
    proc = out[cfg.COL_PROC_TEMP].astype(float)
    wear = out[cfg.COL_WEAR].astype(float)

    # Mechanical power delivered at the spindle, P = tau * omega  [W].
    # Both an under-powered and an over-powered spindle are abnormal, so this is
    # a two-sided signal -- exactly the kind of non-monotonic structure trees
    # handle and a linear baseline struggles with.
    out[cfg.FEAT_POWER] = torque * speed * RPM_TO_RAD_S

    # Temperature differential driving heat rejection [K]. A small differential
    # means the process cannot shed heat into the surrounding air.
    out[cfg.FEAT_TEMP_DIFF] = proc - air

    # Accumulated strain on the tool: minutes in service weighted by the load
    # carried during them [min*Nm].
    out[cfg.FEAT_STRAIN] = wear * torque

    # Specific loading: torque demanded per unit of rotational speed. High
    # values mean the machine is being asked to cut hard while turning slowly.
    out[cfg.FEAT_TORQUE_PER_SPEED] = torque / speed

    # Cooling adequacy: power dissipated per kelvin of available differential.
    # The differential never approaches zero in this dataset (observed range
    # 7.6-12.1 K) so the ratio is numerically safe.
    out[cfg.FEAT_COOLING_INDEX] = out[cfg.FEAT_POWER] / out[cfg.FEAT_TEMP_DIFF]

    # Ordinal encoding of machine quality, kept alongside the one-hot version
    # for interpretation convenience (tree models benefit from the ordering).
    out[cfg.FEAT_TYPE_ORD] = out[cfg.COL_TYPE].map(cfg.TYPE_TO_ORDINAL).astype(int)

    return out


def build_preprocessor(scale_numeric: bool = True) -> ColumnTransformer:
    """Column transformer: impute + optionally scale numerics, one-hot the type.

    Scaling matters for logistic regression and the Isolation Forest distance
    geometry; it is harmless for the tree ensembles, so a single preprocessor is
    shared and only the linear model requires it.
    """
    numeric_steps = [("impute", SimpleImputer(strategy="median"))]
    if scale_numeric:
        numeric_steps.append(("scale", StandardScaler()))

    return ColumnTransformer(
        transformers=[
            ("num", Pipeline(numeric_steps), cfg.NUMERIC_FEATURES),
            (
                "cat",
                OneHotEncoder(
                    categories=[cfg.TYPE_ORDER],
                    drop="first",
                    sparse_output=False,
                    handle_unknown="ignore",
                ),
                cfg.CATEGORICAL_FEATURES,
            ),
        ],
        remainder="drop",
        verbose_feature_names_out=False,
    )


def feature_names(preprocessor: ColumnTransformer) -> list[str]:
    """Human-readable names for the transformed matrix, for SHAP and plots."""
    names = list(preprocessor.get_feature_names_out())
    pretty = {
        cfg.COL_AIR_TEMP: "Air temp (K)",
        cfg.COL_PROC_TEMP: "Process temp (K)",
        cfg.COL_SPEED: "Rotational speed (rpm)",
        cfg.COL_TORQUE: "Torque (Nm)",
        cfg.COL_WEAR: "Tool wear (min)",
        cfg.FEAT_POWER: "Mechanical power (W)",
        cfg.FEAT_TEMP_DIFF: "Temp differential (K)",
        cfg.FEAT_STRAIN: "Wear x torque strain",
        cfg.FEAT_TORQUE_PER_SPEED: "Torque per rpm",
        cfg.FEAT_COOLING_INDEX: "Cooling load index",
        "Type_M": "Machine type = M",
        "Type_H": "Machine type = H",
    }
    return [pretty.get(n, n) for n in names]


def X_frame(df: pd.DataFrame) -> pd.DataFrame:
    """Select exactly the model input columns, in a stable order."""
    missing = [c for c in cfg.FEATURE_COLS if c not in df.columns]
    if missing:
        raise KeyError(f"Frame is missing engineered columns: {missing}. "
                       "Call add_physics_features first.")
    return df[cfg.FEATURE_COLS].copy()


__all__ = [
    "add_physics_features", "build_preprocessor", "feature_names", "X_frame",
    "RPM_TO_RAD_S",
]
